server:
  port: 8082

spring:
  datasource:
    url: jdbc:mysql://localhost:3308/note
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      # 连接池的配置信息
      # 初始化大小 最小  最大
      initial-size: 5
      min-idle: 5
      maxActivate: 20
      # 配置获取连接等待超时的时间
      maxWait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      timeBetweenEvictionRunsMillis: 60000
      # 配置一个连接的池中最小生存的时间，单位是毫秒
      minEvictableldleTimeMills: 3000
      validationQuery: SELECT 1
      testWhileldle: true
      testOnBorrow: false
      testONReturn: false
      # 打开PSCache ，并且指定每个连接上PSCache的大小
      poolPreparedStatements: true
      maxPoolPreparedStatementPerConnectionsSize: 10
      # 配置监控统计拦截的filters,去掉后监控界面sql无法统计,wall用于防火墙
      filters: stat,wall,slf4j
      # 通过connectProperties属性来打开mergeSql；慢Sql记录
      connectionProperties: druid.stat.mergeSql\=true;druid.stat.slowSqlMillis\=500
      # 配置DruidStatFilter
      web-stat-filter:
        enabled: true
        url-pattern: "/*"
        exclusions: "*.js,*.gif,*.jpg,*.bmp,*.png,*.css,*.ico,/druid/*"
      stat-view-servlet:
          # IP白名单(没有配置或者空，则允许所有访问)
          allow: 127.0.0.1,192.168.163.1
          # 黑名单(存在共同时候,deny优先于allow)
          deny: 182.168.1.188
          # 禁用HTML页面的"Reset All"功能
          reset-enable: false
          # 登录名
          login-username: admin
          # 登录密码
          login-password: 123456
  mvc:
    view:
      prefix: /WEB-INF/
      suffix: .jsp
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
    encoding: UTF-8


mybatis:
  mapper-locations: classpath:mybatis/*.xml
  type-aliases-package: com.xiaoli.pojo

